### ISSUE TITLE
Enhancement: output file

### ISSUE THREAD

**Issue by chinezbrun** [adamcharnock/mate3#1]
Is possible to have option on CLI to generate an output file (txt, json)?

**Comment by adamcharnock** [comment]
Hi Dan,

As a MacOS/Linux user I would redirect the output as follows:

```
mate3 --host=foo --format=json > my_file.json
```

From your other issue I'm guessing you're on windows. However, a quick google reveals this [should work on Windows too](https://helpdeskgeek.com/how-to/redirect-output-from-command-line-to-text-file/). Perhaps give it a go?

In the above case you'll get one JSON object line per line in the file. To use the data you'll need to read each line of `my_file.json` as text then parse it as JSON, rather than try to parse the entire contents of the file as JSON.

**Comment by adamcharnock** [comment]
Hi @chinezbrun,

I'm going to close this issue as I think output redirection should be sufficient in this case.

---

If more people see this as being a problem then definitely comment here, detailing why output redirection is not sufficient for your use-case.

Anyone requesting a change/addition to the output formats should open a new issue.
